name 'awesome_customers_delivery'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures awesome_customers_delivery'
long_description 'Installs/Configures awesome_customers_delivery'
version '0.1.0'

depends 'chef-sugar'
depends 'firewall', '~> 2.4.0'
depends 'httpd', '~> 0.3.4'
